site_name: Aarmaa IT - Docs
site_description: Juhendid, Näpunäited, etc

theme:
  name: mkdocs

nav:
  - Avaleht: index.md
  - Juhendid:
    - Serveri Seadistus: seadistus.md
  - Näpunäited:
    - Ubuntu 26.04: ubuntu.md

plugins:
  - search
